FROM        amazoncorretto:22

LABEL       author="Doom2615" maintainer="doom@atbphosting.com"
LABEL       org.opencontainers.image.source="https://github.com/Doom2615/atbp-images"
LABEL       org.opencontainers.image.licenses="MIT"

# Added --allowerasing to resolve the curl-minimal vs curl conflict
RUN         dnf upgrade -y --releasever=latest --allowerasing \
            && dnf install -y --releasever=latest --allowerasing \
            curl \
            ca-certificates \
            openssl \
            git \
            tar \
            sqlite \
            fontconfig \
            freetype \
            libstdc++ \
            freetype-devel \
            lsof \
            tzdata \
            iproute \
            gcc \
            gcc-c++ \
            automake \
            make \
            libtool \
            shadow-utils \
            && dnf clean all \
            && rm -rf /var/cache/dnf \
            && useradd -m -d /home/container container

ENV         LC_ALL=en_US.UTF-8
ENV         LANG=en_US.UTF-8
ENV         LANGUAGE=en_US.UTF-8

USER        container
ENV         USER=container HOME=/home/container
WORKDIR     /home/container

COPY        ./entrypoint.sh /entrypoint.sh
CMD         [ "/bin/bash", "/entrypoint.sh" ]
