FROM        amazoncorretto:25.0.2-al2023

LABEL       author="Doom2615" maintainer="doom@atbphosting.com"
LABEL       org.opencontainers.image.source="https://github.com/Doom2615/atbp-images"
LABEL       org.opencontainers.image.licenses="MIT"

RUN         dnf upgrade -y \
            && dnf install -y \
               # Replacement for "Development Tools"
               binutils gcc gcc-c++ make automake libtool \
               # Your required packages
               curl ca-certificates openssl git tar sqlite-devel \
               fontconfig freetype freetype-devel lsof tzdata iproute \
               libstdc++-devel \
               # Required for your ENV LC_ALL=en_US.UTF-8 to actually work
               glibc-langpack-en \
            && dnf clean all \
            && rm -rf /var/cache/dnf \
            && useradd -m -d /home/container container

ENV         LC_ALL=en_US.UTF-8
ENV         LANG=en_US.UTF-8
ENV         LANGUAGE=en_US.UTF-8

USER        container
ENV         USER=container HOME=/home/container
WORKDIR     /home/container

COPY        ./entrypoint.sh /entrypoint.sh
CMD         [ "/bin/bash", "/entrypoint.sh" ]
